[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48086
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'RFID LLRP Inventory Service: http://localhost:48086'
Timeout = '30s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

# Database is require when Store and Forward is enabled
# SecretStore is required when Store and Forward is enabled and running with security
# so Database credentials can be pulled from Vault.

[Clients]
    [Clients.edgex-core-data]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48080

[Trigger]
Type="edgex-messagebus"
SubscribeTopics="events, edgex/events"
    [Trigger.EdgexMessageBus]
    Type = 'zero'
        [Trigger.EdgexMessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[ApplicationSettings]

[AppCustom]
DeviceServiceName = "edgex-device-rfid-llrp"
DeviceServiceURL = "http://localhost:51992/"
MetadataServiceURL = "http://localhost:48081/"
AdjustLastReadOnByOrigin = true
DepartedThresholdSeconds = 600
DepartedCheckIntervalSeconds = 30
AgeOutHours = 336
MobilityProfileThreshold = 6.0
MobilityProfileHoldoffMillis = 500.0
MobilityProfileSlope = -0.008
Aliases = { SpeedwayR-10-EF-20 = {"1" = "cccBackStock"} }

